### ISSUE TITLE
Extension crashes Chrome when used with Breevy

### ISSUE THREAD

**Issue by thorrrr** [jswanner/DontFuckWithPaste#10]
Hi 
Love your extension but had to switch it off as the extension crashes Chrome when used with Breevy.

See [here ](https://dl.dropboxusercontent.com/u/92887/Faststone%20Capture/Crashing%20with%20Breevy.wmv)

If i turn off your extension Breevy works, as a text replacer i use it 100 of times a day so I need it more than your extension. Was hoping they could both work together.

AG

**Comment by jswanner** [comment]
Wow, late reply, sorry about that.

Unfortunately, I'm not familiar with Breevy, and since it's not open source software, I can't tell exactly what it's doing. Does this happen on sites that this extension has been configured to not run on as well, or does it only happen when the extension is actively running on a site?

**Comment by jswanner** [comment]
With the release of version 2, the extension is no longer active on any site by default, which should alleviate this problem.
