### ISSUE TITLE
Can't paste email in registration form

### ISSUE THREAD

**Issue by Ashtonian** [jswanner/DontFuckWithPaste#113]
https://ozarksecc.smarthub.coop/Login.html#registration: 

The email fields seem blocked with the plugin, using brave.

**Comment by jswanner** [comment]
@Ashtonian, sorry to hear you're having trouble. I'm not able to reproduce the problem you are experiencing, that said I am using Chrome on macOS instead of brave on whichever operating system you are using.

From what I can see, they are not blocking "paste" events at all, so this extension will have no affect on that site one way or the other. It's possible they are blocking the keyboard shortcut associated with paste for Windows/Linux computers (control + v), I couldn't find any code that indicated they were but I'm not able to test that as the keyboard shortcut on Mac is different (command + v). If they are blocking the keyboard shortcut then you should still be able to paste via the context menu (right click) and from Paste in the Edit menu.

**Comment by jswanner** [comment]
My apologies... Immediately following me closing this issue I noticed the subject of this issue mentioned "registration" and I realized I was testing the login page instead.

So on their registration page, they are indeed blocking "paste" events in the email field, but this extension correctly circumvents that once activated. At least it does on Chrome, again I'm not a Brave user so I can't test that out to verify it works properly on other browsers. Please check that you have _activated_ the extension for this site, as that's how this extension is intended to be used: https://github.com/jswanner/DontFuckWithPaste#usage

**Comment by Ashtonian** [comment]
Thanks for the response, after adding the site to the white list it does indeed work. 

what are your thoughts on starting a builtin defaults site list ?

**Comment by jswanner** [comment]
The previous major version of this extension had a default list of sites it was configured to run on and those not to run on, and most of the issues created at that time revolved around people wanting to change those defaults. My main motivation for the current major version was to make activating the extension for specific sites as easy as possible, so people could customize the extension to meet their browsing trends, and to get away from the extension having defaults.

You can have an inferior browsing experience by having this extension active on sites that do helpful things with paste events (like GitHub turning a file paste into a file upload). So, having this extension active by default on sites that are currently bad actors can lead to problems down the road if those sites begin doing good things with paste. I also really don't want to try maintaining a repository of all known bad actors around the world when it comes to copy/paste.
