### ISSUE TITLE
Plugin breaks pasting of images on any website

### ISSUE THREAD

**Issue by Nowaker** [jswanner/DontFuckWithPaste#14]
Example websites where one can paste an image from clipboard:
- Slack
- Doorbell

To reproduce, take a screenshot with Spectacle (a KDE 5 tool), then click Copy to Clipboard, then ^V into Slack window.

Can a plugin check what's in the clipboard, and if it's an image, let it hit the default handler?

**Comment by jswanner** [comment]
The way that this extension works is incredibly simple: it hijacks a `paste` event at the earliest possible stage, prevents any other code from receiving the `paste` event, and tells the browser to perform its default behavior for `paste`. And, it's really 3 simple lines of code that accomplish that, all of the other code in this extension is about configuration/settings.

The reason I wrote this extension is to keep sites from blocking `paste` events, granted some sites hook into `paste` events and provide helpful/useful side-effects as a result. But, this extension has no way to know what a site will do with a `paste` event programmatically, instead it just there to let the browser perform its default behavior.

Pasting an image and having it turned into a file upload is not a default browser behavior, it's a useful thing that some apps are doing, and something I'm a big fan of. What I don't want to do is have this extension making decisions about what to do based on the contents of the clipboard.

Instead, I would say either whitelist the sites you use that are good with `paste` events, or whitelist everything and blacklist those sites you use that are bad with `paste` events.

**Comment by Nowaker** [comment]
I understand it's 3 simple lines of code... but it doesn't have to be like that, correct? So my question is still valid - can a plugin check what's in the clipboard, and if it's an image, let it hit the default handler?

**Comment by vermeer-grange** [comment]
+1 I'm affected when pasting images in Slack and Trello.

We should either
-let images pass in any case, like suggested by Nowaker (good solution)
or
-build a default whitelist of websites (slack, doorbell, trello...) - not a great solution because it will still break on other sites and be really confusing for users to figure out that this bug comes from this extension (I really took a long time to figure it out myself)

**Comment by jswanner** [comment]
Version 1.0 of this extension added configurability, so users could specify which sites this extension should or should not run on, but I also defaulted those settings so that version 1.0 matched the behavior of the previous versions of this extension. Those settings basically blacklist all sites, and then specify a small list of sites that are whitelisted. This set up a situation where the most common request I get now is to add more sites to the default whitelist.

This request is to basically whitelist specific kind of clipboard content, regardless of the rules for the site. That not only takes this extension into territory that I'd rather not go (with added complexity, and the creepiness of having an extension that was inspecting the contents of my clipboard), but I also think it is a work-around (not a solution) to a much more fundamental problem. That problem being that I think the number of sites that people commonly use that are good with `paste` far outnumber the number of sites that are bad with `paste`, yet this extension's default settings implies the opposite: most sites are bad and a few are good.

As of right now, I believe a better future for this extension would be to whitelist all sites and provide a better/quicker user experience to add sites to the blacklist. This hasn't been done yet due to a lack of free time on my part (and lack of motivation when there is some free time).

**Comment by Nowaker** [comment]
Thanks for your input @jswanner. Sounds good overall, here's my comment on this one particular thing:

> the creepiness of having an extension that was inspecting the contents of my clipboard

There's nothing creepy here because it's an open source project. Not a proprietary code that does God-knows-what.

**Comment by diversario** [comment]
Holy crap, I spent a month being confused about why I can't paste images into Twitter anymore and it this was this. Other sites worked fine, just twitter was broken. So happy to have found the cause!

**Comment by kieserjw** [comment]
Same here.  So many lost images.  Glad to have found the solution

**Comment by jswanner** [comment]
With the release of version 2, the extension is no longer active on any site by default, which should alleviate this problem.
