### ISSUE TITLE
Breaks Copy/Paste with Ace Editor

### ISSUE THREAD

**Issue by thejsj** [jswanner/DontFuckWithPaste#18]
Was having trouble copy/pasting code in ace editor and realized this had to do with this plugin.

Repo steps:

1. Go here: https://ace.c9.io/#nav=about
2. Copy code in editor
3. Pate it right back

Expected: Code is pasted
Result: Nothing is pasted

Will try to see if I can fix it, but wanted to post the issue first.

**Comment by jswanner** [comment]
This extension works by preventing a site's JavaScript from receiving `paste` events, this is done in order to prevent the site from blocking the browser's default behavior for those events. There are sites that listen for `paste` events and do useful things with those events. For those sites you do not want this extension active, which is why you can configure this extension to disable itself on certain sites.

You will want to add an exclusion pattern for `https://ace.c9.io/.*` (or something similar that):

![image](https://cloud.githubusercontent.com/assets/261/20008804/5a3cc870-a278-11e6-82a6-8e97dcfae991.png)

**Comment by jswanner** [comment]
To add the exclusion pattern:

1. Go to chrome://extensions/
2. Click on the "Options" link for this extension
