### ISSUE TITLE
Breaks copy-paste in Editey web apps

### ISSUE THREAD

**Issue by boghyon** [jswanner/DontFuckWithPaste#19]
**Steps to reproduce**:
1. Get one of the Editey's web apps, e.g. [JavaScript Editey](https://chrome.google.com/webstore/detail/javascript-editey/hkihmgfcedmdoaogcjdljeeacngbhinc)
2. Create a new Editey file (--> A new tab is opened with the URL "javascript.editey.com/file/...")
3. Type some text and try to copy-paste it.

**Expected**: The copied text gets pasted in the web app.
**Result**: Neither copy nor paste work. Nothing gets pasted. When I copy, instead of the selected text, I get a tofu block when I paste it in a native notepad. I tried to copy paste the selected text from the context menu, didn't work either.

**Chrome**: 54.0.2840.87 m (64-Bit) on Windows 10

The only workaround to solve this problem is to exclude Editey-related domains from the extension options.

**Comment by jswanner** [comment]
I don't have Editey installed in order to reproduce, but I'm going to assume this is similar to #18.

This extension works by preventing a site's JavaScript from receiving paste events, this is done in order to prevent the site from blocking the browser's default behavior for those events. There are sites that listen for paste events and do useful things with those events. For those sites you do not want this extension active, which is why you can configure this extension to disable itself on certain sites.

1. Go to chrome://extensions/
2. Click on the "Options" link for this extension
3. Add an exclusion pattern for `https?://javascript.editey.com/.*` (or something similar that).

**Comment by boghyon** [comment]
Thank your for your quick answer. If using the exclusion list is the only workaround, wouldn't it be nice to add such reported websites to  [default.js](https://github.com/jswanner/DontFuckWithPaste/blob/master/defaults.js) for future releases? So that users don't get surprised, if something doesn't work (and then defining a custom regex is not really user-friendly). Furthermore, if a user has many Chrome extensions, it's not obvious for him that it's this extension that breaks the copy-pasting on certain websites.

The regex I defined for Editey web apps looks like this: `https?:\/\/.*\.editey\.com\/.*`.

**Comment by jswanner** [comment]
Actually, adding extra patterns to defaults.js wouldn't help, as that's only used when someone first installs the extension. Someone's exclusion list wouldn't be updated when the extension is updated (unless they happen to click on "Use Default Settings" after the update). The values in the defaults are there more for backwards compatibility to older versions of this extension, when there wasn't a settings page.

**Comment by jswanner** [comment]
With the release of version 2, the extension is no longer active on any site by default, which should alleviate this problem.
