### ISSUE TITLE
Please protect copy as well

### ISSUE THREAD

**Issue by ahrenstein** [jswanner/DontFuckWithPaste#20]
AWS IAM console is an example of where the copy function is blocked. Can you add support to prevent copy blocking as well?

**Comment by jswanner** [comment]
This extension already does the same thing for `copy` events as it does for `paste` events: prevent the site from receiving those events so that they can not block them.

But, there are other ways to effectively block copying of content besides hooking into `copy` events: a site can hook into the various key events and block the browser from recognizing those key presses. Unfortunately, I'm not comfortable expanding this extension to all those events, as that will have a much greater [potentially negative] impact on users' web browsing experience compared to what this extension currently does.

I was poking around in the AWS console, and could not find an example of where I couldn't copy text. Could you be more specific as to where you experienced this, so that way I can know for sure what's preventing copy?

**Comment by ahrenstein** [comment]
Ah interesting. Sure thing. I went to IAM Policies and tried to edit a policy document

    https://console.aws.amazon.com/iam/home?region=us-east-1#policies/arn:aws:iam::ACCOUNTNUMBER:policy/POLICYNAME

CMD+C and CMD+V don't work in the latest Chrome. Also the right click context menu has Cut, Copy and Paste all greyed out. Select All works though.

**Comment by jswanner** [comment]
Thanks for that.

I do see that they alter the context menu, greying out Cut, Copy, and Paste. And, it's true you cannot paste in that box, but that's because the box is not a form field, the text is just being displayed to you. I was able to copy text using command-c (I had to paste it elsewhere to confirm).

**Comment by ahrenstein** [comment]
Interesting. I wonder what's different for me. I'll have to mess with my other plugins to see what's broken. Thanks
