### ISSUE TITLE
Publish to Firefox?

### ISSUE THREAD

**Issue by MichaelAquilina** [jswanner/DontFuckWithPaste#22]
Considering the simplicity of this extension I would assume that it would take little to no work to get this working on firefox. Could you please publish this on the Firefox store?

**Comment by jswanner** [comment]
It had been a very long time since I had looked at Firefox's add-on system, so I had no idea that support for Chrome style extensions had been added. And, you're right, it does seem like very little work is needed to get it working. I still need to do some more testing, but this is certainly something I'm considering.

**Comment by MichaelAquilina** [comment]
Glad to hear that! I think it should almost work as is from what I understand from the docs. Its mostly a matter of uploading it to their store.

**Comment by aaronraimist** [comment]
@MichaelAquilina It is uploaded and will be available here soon after review by Mozilla: https://addons.mozilla.org/en-US/firefox/addon/don-t-fuck-with-paste/

You can close this issue.

**Comment by singron** [comment]
This can be closed right?

**Comment by jswanner** [comment]
Please see: https://addons.mozilla.org/en-US/firefox/addon/don-t-fuck-with-paste/
