### ISSUE TITLE
Not pasting Credit Card details

### ISSUE THREAD

**Issue by suktrd** [jswanner/DontFuckWithPaste#23]
Not working for online transactions in Chrome

**Comment by jswanner** [comment]
I would need to know more specifics of where you are experiencing a problem in order to give you a more detailed explanation of the situation.

There are many ways in a site may prevent a `paste` event from occurring. This extension prevents a site from blocking `paste` (and `copy`) events specifically, but a site could, for instance, prevent the browser from recognizing the individual key strokes (ctrl-v / cmd-v) thereby blocking you from pasting in a different way.

Wherever you are experiencing this problem, can you paste via the context menu (right click)?

**Comment by jswanner** [comment]
Closing until more specifics are given.
