### ISSUE TITLE
Extension actually blocks copy

### ISSUE THREAD

**Issue by Zoooook** [jswanner/DontFuckWithPaste#27]
When viewing a text file on `<org>.slack.com/files/<name>/<stuff>/-.txt`

If I select more than 1000 characters and copy it, the single character '-' is placed on the clipboard. Problem goes away when I exclude the site in options.

**Comment by jswanner** [comment]
I am able to reproduce the issue you reported, unfortunately there's nothing I can do to "fix" this issue, other than help you to configure the extension properly to make sure it's excluded from all Slack sites.

Slack is using CodeMirror (https://codemirror.net/) to display the file and this extension is blocking CodeMirror's `copy` event handling. Which wouldn't be a problem except for whatever reason, once you've selected more than 1000 characters, CodeMirror manipulates what the browser thinks is the selected text to only include "-", and then in their `copy` event handling the content you really want is put into your clipboard.

You can see CodeMirror's manipulation of selected text by highlighting some text, and then tell the browser to "Look Up" or "Search With Google". If you select a small number of characters that browser action will do what you want, but once you select more than 1000 characters you'll be looking up "-".

So, since CodeMirror is hooking into a bunch of browser events, in order for you to have the desired copy behavior, you need to make sure all of CodeMirror's event handling is allowed to happen. This extension will interfere with CodeMirror's `copy` and `paste` events, which you don't want.

**Comment by Zoooook** [comment]
Hey, thanks for the response, sorry I'm just now seeing it.
