### ISSUE TITLE
Can't paste images on WhatsApp web

### ISSUE THREAD

**Issue by manutenfruits** [jswanner/DontFuckWithPaste#31]
I usually do screenshots to my clipboard or copy images directly and paste them on WhatsApp web to send them, but this extension prevents me from doing so. Let me know if you need more details.

**Comment by jswanner** [comment]
@manutenfruits, you can configure the extension to not run on WhatsApp:

1. Go to chrome://extensions/?options=nkgllhigpcljnhoakjkgaieabnkmgdkb
1. In the 2nd box, labeled "Exclude URL Patterns", add `https://web\\.whatsapp\\.com/.*` on its own line

**Comment by manutenfruits** [comment]
Thanks, I was aware of that solution, however I wonder if there is a way of having it work out of the box. I understand it might be a technical limitation overriding the paste handler, but being an extension that _allows_ pasting, it's a bit odd that in this case it _prevents_ pasting

**Comment by jswanner** [comment]
The extension works by preventing a website from hooking into `paste` events, in order to allow the browser's default `paste` event handling to run. The default browser behavior for pasting files is to do nothing.

For websites that hook into `paste` events in order to convert a file in the in clipboard into a file upload, it's better to let the website's `paste` event handling to run than the browser's default handling. So, the extension isn't technically preventing paste in your situation, but it is preventing a useful paste behavior in favor of an useless paste behavior.

People have asked for the extension be modified to look at what's in the clipboard, and for it to do nothing if it's a file being pasted, thereby letting the website's `paste` hooks run if they exist. I do not like that for a few reasons, mostly because it adds a weird 3rd state to the extension: not running on a site, running on a site, running on a site but disabled for some events.

For backwards compatibility with older versions of this extension, the default configuration is to blacklist all sites and whitelist a few. I think the opposite is a better solution: whitelist all sites and blacklist only the troublesome ones. I've been wanting to change the extension to do just that, but I would want the experience of blacklisting a site to be much better, especially for non-technical people.

**Comment by manutenfruits** [comment]
Thanks for taking the time replying, it makes sense. It does one thing and does it good. Maybe at some point it can grow to have a collaborative blacklist like ad blockers have, but that seems too out of scope for such a simple extension right now. I agree, I'll whitelist it. Thanks for your time!
