### ISSUE TITLE
Doesn't fucking work

### ISSUE THREAD

**Issue by Fish-Git** [jswanner/DontFuckWithPaste#33]
The sole reason for me trying this extension was to fix the problem of not being able to right-click and paste into the userid field of Microsoft's sign-in web page:

   https://login.live.com/login.srf

But even with the extension installed and enabled the right-click context menu is STILL missing any type of paste command.

What the FUCK is going on?  Is their form input field not actually a form input field? Is it some type of ActiveX control crap? I fucking HATE these damn web sites that don't allow you to right-click and PASTE data into their web page's input fields!!  Why the fuck are so many web site designers asshole idiots that don't understand the first thing about a good user interface and good security?! Sheesh!

**Comment by Fish-Git** [comment]
Additional info: yes, keyboard Ctrl+V paste works. But that's not the point. The point is,why doesn't the mouse right-click menu contain a paste command? Why doesn't it contain the standard set of commands? Right-clicking anywhere within any _other_ text input field always displays a standard set of commands, with one of those commands of course being "Paste". Why does right-clicking into Microsoft's input field not display a regular right-click context menu with a Paste command?

And the problem occurs _not_ just with Microsoft's web page either. The problem occurs with other sites too. I don't have a list of all of the sites that this problem occurs on, but it's _not_ just Microsoft. It's other web sites too.

Have developers these days completely abandoned the KISS principle? Why do people insist on complicating things (which only ends up breaking things leading to frustrations such as this).

Sheesh!  :(

**Comment by jswanner** [comment]
Hi @Fish-Git, sorry to hear this extension isn't helping you out here.

> What the FUCK is going on? Is their form input field not actually a form input field?

That's pretty much the case. Before you start typing, it's not an input field, instead it's a `<div>` element meant to look like an element with a placeholder; once you start typing that "placeholder" div is hidden and you are then looking at a real input field. That is why the context menu does not contain a "Paste" option, as you are not looking at the context menu for a field, instead it's the same context menu you'd see if you right-clicked on any other part of the page.

> Why the fuck are so many web site designers asshole idiots that don't understand the first thing about a good user interface and good security?! 

I totally agree with you on that feeling, which is why I created this extension in the first place. Unfortunately, there are many ways that developers can interfere with the normal web browsing experience, and there's no way this extension can fix them all. Instead it's pretty narrowly focused on preventing the most direct ways of blocking copy & paste.

That said, the currently released version of this extension is not without its own problems. For backwards compatibility with older versions, the default configuration of this extension is to blacklist all sites and whitelist a few. I think the opposite is a better solution: whitelist all sites and blacklist only the troublesome ones. As I would say there are more sites that do useful things on `paste` events (like GitHub file uploads) than there are sites that do nefarious things.

I have a complete rewrite of this extension to make that second style easier to work with; it's working, but still needs UX love. If you are familiar with using local extensions, you can test it out: https://github.com/jswanner/DontFuckWithPaste/tree/v2.

**Comment by Fish-Git** [comment]
Thank you, Jacob. I appreciate the reply and apologize for venting. I believe have seen other sites(*) which actually did actively prevent _any_ type of pasting into their input fields, so I'm sure your extension is useful. It unfortunately wasn't useful to me in this particular case which is why I apologize most sincerely for my bitching. It wasn't your extension's fault. I'm sure your extension works fine. It's Microsoft's and other sites' fault that use the same technique. (sigh) Oh well. Thanks again and have a nice day and sorry again for bitching.  :)

**Comment by jswanner** [comment]
I should probably start keeping a record of sites that do really stupid things. I can't remember which site it is, but I've been to one a couple times that allows pasting text into fields, but doesn't recognize the pasted text. They use JavaScript to capture each keypresses, accumulate the characters into a variable, and then use that variable on submission (instead of the contents of the input field). So on that site, when you paste text, it doesn't go through their key capturing code, and therefore thinks you haven't filled in a password.
