### ISSUE TITLE
DMV account creation password field paste blocked

### ISSUE THREAD

**Issue by GotGame** [jswanner/DontFuckWithPaste#36]
Tried using the extension/plugin on both Chrome and Firefox. Get popup dialog when trying to paste in password field with "Sorry, this functionality is disabled". DMV is uncharacteristically clever and characteristically annoying with their signup page:

https://www.dmv.ca.gov/FIM/sps/uscfed/usc/self/account/create

**Comment by GotGame** [comment]
Noticed that the page is capturing the right click and only the pressing of the control key, which pops up the dialog box. In Firefox, after a few dialog boxes, it gives the option to prevent the page from creating further dialog boxes. After checking that option, I am able to paste with Control-V and right click, Paste in Firefox.

**Comment by aaronraimist** [comment]
Yeah I was going to say, the paste blocker isn't written very well. I can Command-V paste on that website perfectly fine even without the extension installed.

**Comment by jswanner** [comment]
@GotGame from viewing the source of that page, they are trying to limit browser interactions using `onkeydown` and `onmousedown` attributes of the `input` elements.

There are many ways that a website author can try to control a user's browsing experience, this extension is just meant to prevent a site from blocking `copy` and `paste` browser events -- which is the most direct way for a site to interfere with copying/pasting, but not the only way. Luckily (in a weird way), in addition to blocking control-press they also showed an alert, and as you mentioned, after a site has thrown up a couple alerts, browsers now let you block the site from showing more of them, which gives you a work-around. As for right clicking, they show an alert, but don't actually block it.

As I mentioned before, there are many ways a site can try to interfere w/ copying & pasting, and I don't want this extension to start interjecting itself into keyboard and mouse events, as I'm afraid this extension would break more sites than it fixed if it were to do that.

@aaronraimist, you are able to paste because you are on a Mac and the site author(s) didn't not try to block pressing command, only control.
