### ISSUE TITLE
Not working for https://starconnectcbs.bankofindia.com/

### ISSUE THREAD

**Issue by firehawk895** [jswanner/DontFuckWithPaste#47]
The website is not allowing me to paste. Can you tell me a way to examine the front end code, so I can paste the relevant details here, so we can fix this?

**Comment by jswanner** [comment]
There are a number of ways to block the ability of pasting into fields, this extension is narrowly focused on the most direct approach -- which is to let the browser use its default behavior for `paste` events.

It takes a lot of digging to figure out how a particular site is blocking paste, and I will not be able to give you step-by-step instruction to follow to figure it out. I generally use Chrome's Dev Tools, from its "Elements" panel, you can select an input element, then look at the "Event Listeners" pane, which will show events will trigger a handler. After that, it takes digging through lots of HTML & JS code.

For instance: on the [login page](https://starconnectcbs.bankofindia.com/BankAwayRetail/(S(453erm55zpli2ybpy5l1uu55))/web/L001/retail/jsp/user/RetailSignOn.aspx?RequestId=23207877), they have an event listener for `contextmenu` events on the `document` (which will appear on any element's "Event Listeners" pane), in order to prevent right-click/context-menu.

As for blocking paste, it could be done by listening to `paste` events (which this extension should circumvent), or listening to the various keyboard events to block the keyboard paste combination, or by blocking the context menu as stated above.

**Comment by jswanner** [comment]
It seems that bankofindia.com tries to prevent paste in multiple ways: blocking `paste` events, intercepting keyboard events involving control, blocking `contextmenu` (right-click).

With this extension active, you should be able to use the Edit menu and then select Paste from there. Less than ideal, but the best workaround I can provide.
