### ISSUE TITLE
OK to use wildcard? (*)

### ISSUE THREAD

**Issue by bcsteeve** [jswanner/DontFuckWithPaste#55]
Or is that asking for trouble?  I'm not sure why you went with the blacklist vs whitelist thing.

**Comment by jswanner** [comment]
`.` will make it run everywhere, which is mostly how the default configuration ran before. To exactly match the old default behavior add the following as a rule:

```regexp
https?://(?!.*?\.?facebook\.com|.*?\.?github\.com|.*?\.?google\.com|.*?\.?imgur\.com)
```

But honestly, I would not recommend using either approach. The reason for this new approach is that it's now very easy to activate this extension for an offending site, you just need to click on the extension button, optionally adjust the pattern that's created for you (which is the `origin` of the site's URL), and then click save. The extension will then be active on the page, you don't need to refresh or anything.

**Comment by stalks** [comment]
This extension isn't on my toolbar, I have it hidden under the settings button. Its one of those things that just works. I install it and forget its there.

**Comment by jswanner** [comment]
Having the extension active on sites that do helpful things with copy and paste events (like GitHub and many others) will lead to a degradated browsing experience. See the many issues where people ask for various sites to be whitelisted/ignored.

At least from overall my browsing experience, I come across more sites that do good things with paste than sites that do bad things. And therefore, I feel it’s better for the extension not to interfere unless absolutely necessary, but that wasn’t the default behavior before. I also felt like the workflow for activating the extension on a site could be greatly improved, along with exposing the active/inactive state of the extension for a given site. 

Having the extension button hidden in the Chrome menu is fine, it just requires an extra mouse click in order to interact with the extension’s popup. Using the popup is not required, the extension can be configured from chrome://extensions like it was before.
