### ISSUE TITLE
Display notifications permission

### ISSUE THREAD

**Issue by ArthurGuy** [jswanner/DontFuckWithPaste#59]
The display notifications permission was recently added as a Chrome requirement but there is nothing to explain why it's being requested or what its go to do with the intended purpose of the extension.

**Comment by jswanner** [comment]
It was added so that I could notify people of a major change in behavior, by linking to the [Wiki page](https://github.com/jswanner/DontFuckWithPaste/wiki/Version-2.0) about the upgrade.

Since I have no plans of future notifications, I'll be removing that upgrade notification and the permission for notifications soon.

**Comment by jswanner** [comment]
You are welcome to leave additional comments on the issue, but I'll be closing it for now.

**Comment by ArthurGuy** [comment]
That's awesome, thank you
