### ISSUE TITLE
Not working on https://www.onlinesbi.com/

### ISSUE THREAD

**Issue by amtkm** [jswanner/DontFuckWithPaste#66]

**Comment by amtkm** [comment]
Yes, it was working last month, was it because of updated code or something in browsing like web language update is the reason for not working?

**Comment by jswanner** [comment]
I cannot log into https://www.onlinesbi.com/, so I'm using https://corp.onlinesbi.com/saral/login.htm (after clicking "Continue to login"), for my testing.

There are many ways that a website author can try to control a user's browsing experience, this extension is just meant to prevent a site from blocking `copy` and `paste` browser events -- which is the most direct way for a site to interfere with copying/pasting, but not the only way. As @ThomasMldr mentioned, they are also blocking the `contextmenu` event (right click). Taking a quick look at their JavaScript, they are also trying to prevent copy, cut, and paste by listening to keyboard events involving the Control key. Since I'm using a Mac, I'm able to paste when this extension is active because the key combination is Command+v. For non-Mac computers, with this extension active, you'd need to use the Edit menu then select Paste from there.

I don't want this extension to start interjecting itself into keyboard and mouse events, as I'm afraid this extension would break more sites than it fixed if it were to do that.

**Comment by amtkm** [comment]
Awesome! It's working now from Edit menu method. Thanks!!

**Comment by jswanner** [comment]
Glad to hear.
