### ISSUE TITLE
Stopped working last version

### ISSUE THREAD

**Issue by Grambile** [jswanner/DontFuckWithPaste#67]
Since 2 days ago this extension doesnt work anymore in marathonbet. Not sure in other pages, I just used it there.

**Comment by jswanner** [comment]
@Grambile, can you provide an example URL of where it's not working? Since I don't have an account, I don't see many forms beyond those for login & signup -- both of which allow for pasting even without this extension.

I published an update of this extension yesterday, but if you have been experiencing problems for longer then it might be that the site is preventing paste by some other means than just blocking `paste` events.

In order to ensure the extension is configured properly: what's the color of the icon when you visit marathonbet (blue or grey)? What rules do you have setup? You can see them all by going to this URL: chrome://extensions/?options=nkgllhigpcljnhoakjkgaieabnkmgdkb

**Comment by Grambile** [comment]
Hi, it seems that yo changed it so now I have to add the url, right? Before I just had to enable the addon and thats it. Now it works.

The example url was that same one, the login form.
