### ISSUE TITLE
Analytics to see common websites that block pasting

### ISSUE THREAD

**Issue by nitrocode** [jswanner/DontFuckWithPaste#73]
I use this extension because I use a password manager to create passwords and login and so it's useful for websites where it's blocked for changing passwords, logging in, security questions, etc.

After [reading this](https://www.troyhunt.com/the-effectiveness-of-publicly-shaming-bad-security/), it would be nice to have an opt-in analytics for custom urls for this extension to build a global list. That list could then be used similar to adblocking lists and hopefully be a list to shame companies into allowing us to paste.

@jswanner thoughts?

**Comment by jswanner** [comment]
I've had others suggest similar things to me before (although, I do believe you are the first to do so in an issue). This is not something I'm interested in doing, and for a couple reasons. Firstly, I don't want to take on the responsibility of maintaining a global list; this is not a business effort for me, I don't want it to take up more of my time than it already does. Secondly, I've already had enough people thinking this extension is keeping track of their browsing history, I certainly don't want to build in something that _actually_ sends data to a server somewhere.

**Comment by nitrocode** [comment]
Understandable. Would you allow importing a list of expressions from a website? and export a list of expressions to a file? or accept a PR to do so?

**Comment by jswanner** [comment]
I'm fine with a simple export/import process. Adding some kind of subscription mechanism does not sound appealing, due to the complexity of dealing with local changes and such.

**Comment by jswanner** [comment]
I'm sure some people encounter far more bad actors than I do, but I only have 2 sites currently configured for this extension, and I'm only on those sites once every month or 2.

This extension can cause more harm than good if it's running on sites/pages it shouldn't be, which is why I tried to make it easier for people to configure it for themselves (granted, knowledge of Regular Expressions is a barrier). 

It's a pretty quick process to activate this extension for the current site you are visiting, so much so that I would rather activate it as needed than have it unknowingly running on more sites than needed.
