### ISSUE TITLE
Feature Request: Fix New Gmail

### ISSUE THREAD

**Issue by Sushubh** [jswanner/DontFuckWithPaste#77]
I am not sure if this extension can help with the new annoyance in new Gmail but here is the issue that I face on it (and friends have confirmed that they can replicate it at their end). This is not related to pasting. But copying text. But since I am trying to paste the text into another browser tab, I thought you might be able to look into it and see if it can be fixed. 

Basically what is happening is that Gmail is messing up with selection of text that you are trying to copy. Most of the times the selection just disappears (text gets unselected). Sometimes, Gmail would expand the selection to include images and text content around the text while you are trying to select the text. The only option is to reselect the text. 

This seems to happen only on freshly opened unread mails. To replicate: 

Open (new) Gmail. 
Locate an unread mail. 
Open it. 
Select some text in the mail. 
Wait for a second. 
Gmail unselects the text. This does not happen every single time. But it does happen more than 7-8 times out of ten. If you reselect, Gmail does not interfere again. If the mail was opened previously, it does not happen from my experience. This issue has become such a major annoyance that I tend to do a Control+A, wait for a second and two and then proceed with copying the text that needs to be pasted elsewhere. 

I have managed to replicate this issue in Chrome and Firefox. In incognito modes with no extensions interfering with browser elements. 

If other users of this app are reading this post, I request them to try to replicate this issue and post their experience. Thanks.

**Comment by jswanner** [comment]
I keep forgetting to try to reproduce this problem while I have an unread email. If you activate the extension for any particular site, it will hook into `copy`, `cut` & `paste` events, so that the browser's default will be used. You probably _don't_ want to activate this extension for Gmail though, as they probably do helpful things on `paste` events that you want to preserve. This extension doesn't currently let you declare which specific events you want it to hook into for any particular site, as the configuration for that seems like it would be overly cumbersome for rare benefit.

**Comment by Sushubh** [comment]
yeah. i guess it's time to switch to a desktop client for email because this issue is driving me crazy and trying to fix it is likely to break a lot more things. thanks though.

**Comment by jswanner** [comment]
I would suggest looking to see if there are any Tampermonkey/Greasemonkey scripts that can remedy the situation.
