### ISSUE TITLE
Defiant site

### ISSUE THREAD

**Issue by zfLQ2qx2** [jswanner/DontFuckWithPaste#89]
Concur seems to go out of their way to clear the password field if not manually typed. 

https://www.concursolutions.com/nui/signin?lang=

**Comment by jswanner** [comment]
@zfLQ2qx2,

I was not able to reproduce the problem you were describing, but I have experienced sites that do something along those lines. Mostly what I've seen is sites that listen to keyboard events for the username/password fields in order to flip a flag to indicate a key was pressed for that field, and the submit event handler checks that those flags were flipped. It's a silly thing for sites to concern themselves with, as it can interfere with password managers ability to fill in those fields.

While that kind of behavior is frustrating and lessens the browsing experience, it's a bit out of the scope of what this browser extension is intended purpose.

If I misunderstood the problem you are having, feel free to update & reopen the issue.
