### ISSUE TITLE
Doesn't work on this banking website

### ISSUE THREAD

**Issue by marar** [jswanner/DontFuckWithPaste#93]
Works on other websites that I've tried, but this one is proving very stubborn.

https://retail.onlinesbi.com/retail/login.htm

Click on CONTINUE TO LOGIN and try pasting in any of the three fields. Right clicking on any of those fields brings up a pop up that says "This function is not allowed here."

The extension is definitely active; the icon has turned blue. This is the pattern used:

https://retail\.onlinesbi\.com

Thanks in advance, and thanks for creating this!

**Comment by jswanner** [comment]
@marar, sorry for the late reply. Unfortunately, you're not the first to report problems with onlinesbi, it also came up in #66.

There are many ways that a website author can try to control a user's browsing experience, this extension is just meant to prevent a site from blocking `copy` and `paste` browser events -- which is the most direct way for a site to interfere with copying/pasting, but not the only way. There are also other ways to trigger `copy` & `paste` events besides the keyboard shortcut: you can use the context menu (right click) and use the browser's Edit menu.

Looking at their JavaScript, they are also preventing copy, cut, and paste by listening to keyboard events involving the <kbd>control</kbd> key. They are also blocking the contextmenu event (right click). Since I'm using a Mac, I'm able to paste when this extension is active because the key combination is <kbd>command</kbd><kbd>V</kbd>. For non-Mac computers, with this extension active, you'd need to use the Edit menu then select Paste from there.

I don't want this extension to start interjecting itself into keyboard and mouse events, as I'm afraid this extension would break more sites than it fixed if it were to do that.

**Comment by chriswayg** [comment]
Thanks for making the extension! Similar problem here: https://online.bdo.com.ph/sso/login

1Password initially pastes it and BDO deletes it from the form. Pasting it again works, but it will still fail. Pasting it and then pressing the space bar at the end of the password somehow allows it to be recognized as a manually typed password. So with a bit of back and forth it finally kinda works with your extension. - The banks really want to prevent us from using secure passwords :-(

**Comment by jswanner** [comment]
@chriswayg, while I do need the extension active in order to paste into the password field, I don't need it for 1P to fill in the field (I believe their extension modifies form field `value` properties directly). Which 1Password extension are you using?

**Comment by chriswayg** [comment]
@jswanner Interesting, I'm using this one: 1Password extension (desktop app required) from the Chrome webstore, which works only after pasting the password twice and pressing the space bar. 

I also tried this: 1Password X – Password Manager (on Linux), but I cannot find any way to paste a password. 

(both while your extension is active)

**Comment by marar** [comment]
@jswanner, thank you for your response and explanation. Using Chrome's Paste function in the Edit menu works perfectly, so that's a useful workaround.

How annoying is this though! It's not just password fields, it looks like onlinesbi, and a few others, also block paste in fields where you have to enter account numbers for funds transfers. Typing in long account numbers is a recipe for disaster - it's so easy to make mistakes there instead of just copying and pasting (from an email or an IM).

Great extension btw, and thanks!

**Comment by marar** [comment]
Closing issue as the query is resolved.
