### ISSUE TITLE
Doesn't work here

### ISSUE THREAD

**Issue by CholoTook** [jswanner/DontFuckWithPaste#95]
https://www.nestpensions.org.uk/schemeweb/NestWeb/faces/secure/USER_REG/pages/signupAsEmployer.xhtml

It's driving me crazy. Their pathetic attempt at security guarantees weak passwords.

Thanks

**Comment by jswanner** [comment]
@CholoTook, I do see that with this extension inactive that I cannot pasted into their confirm fields, but once I activate the extension I am able to do so.

I did not dig into their JavaScript code to see if perhaps they are also listening for the <kbd>Ctrl</kbd><kbd>V</kbd> key presses, and perhaps they are not doing the same for <kbd>Command</kbd> and therefore it's working for me because I'm using a Mac. If that's the case, then you can paste using the browser's Edit > Paste menu.

**Comment by CholoTook** [comment]
Hey! Works for me now. Perhaps after activating the extension I needed to reload the page (which I thought I did). Anyway, many thanks. You're doing Gods work my friend!
