### ISSUE TITLE
Interferes with GMail website paste

### ISSUE THREAD

**Issue by Taomyn** [jswanner/DontFuckWithPaste#97]
When the extension is enabled and composing an email, I cannot paste images into my mail. Disable it, and the paste works.

I'm using Brave browser, but I tested with Edge and it's the same problem.

**Comment by jswanner** [comment]
@Taomyn, there's no reason to have the extension configured so that it's active while on GMail. The whole reason for the extension's configuration mechanism is so that you only activate the extension on site's the do bad things with `paste` events (mainly blocking the paste from happening). You don't want the extension active on sites that do good things with `paste` events (like GMail and GitHub converting file pastes to file uploads).

While on GMail, if you click on the extension's menu button, the popup should display an delete button ("X") on the right side of whichever patterns are matching the current site:

![image](https://user-images.githubusercontent.com/261/79784990-fbb99d00-82f7-11ea-94ad-fdddda2fbcad.png)

You'll want to click on that "X" to disable the extension while on GMail. If you happen to have multiple patterns that are activating the extension on GMail then you'll need to repeat that process until the extension is disabled and its menu button has turned grey.
