### ISSUE TITLE
class="noSelect" impairs copying

### ISSUE THREAD

**Issue by raulvasquez** [jswanner/DontFuckWithPaste#98]
I have a site I frequent that is using class="noSelect" so I cannot copy text out of their articles. Should this undo that? Or am I better off trying to disable that with something like ublock origin?

**Comment by jswanner** [comment]
@raulvasquez, is this site publicly accessible for me to investigate? If so, what's the URL?

An HTML tag having `class="noSelect"` has no effect on its own.  HTML elements with that class can be selected in CSS in order to have styles modifications applied to it, they can also be selected in JavaScript in order to be manipulated that way.

It's the site's JavaScript that would need to be inspected to see what it's doing with HTML elements that have that `noSelect` class. If the JavaScript is doing something like:

```javascript
element.addEventListener("copy", function(e) {
  e.preventDefault();
  return false;
});
```

Then yes, this extension will circumvent that kind of copy blocking.

**Comment by raulvasquez** [comment]
@jswanner the site is private.

To clarify, I am able to copy the text if I delete that class. It does not appear the website is doing anything to prohibit actually being able to copy text other than removing the ability to select what you want with my mouse or CTRL-A. 

There is not much too it:

```
<div id="article" class="noSelect">
```

**Comment by jswanner** [comment]
ublock origin isn't really going to be able to help you here.

Chrome used to support user stylesheets that you could have used for this purpose. Instead, you might want to try something like: https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb?hl=en
