### ISSUE TITLE
doesn't work on https://www.filecroco.com/

### ISSUE THREAD

**Issue by tuchit** [jswanner/DontFuckWithPaste#99]

**Comment by jswanner** [comment]
@tuchit, since you didn't provide details about what's not working, I'm left to guess what the problem is you are experiencing.

This extension circumvents the most straight-forward approaches a website author can take to prevent copy, cut, and paste functionality. This extension does not try to circumvent all means by which a website author can take to prevent that functionality, partly because there are so many ways in which a website author can try to prevent those actions but also because this extension could end up causing more harm to your browsing experience if it did try to circumvent all the possible ways. Additionally, this extension generally allows for some workarounds for copy, cut, and paste when active event if keyboard shortcuts don't work (such as through right click or Edit menu).

All that said, I'm guessing the problem you ran into on that site isn't actually with copy, cut, or paste directly, but rather with text selection. Which, I'll admit, selecting text is quite relevant when it comes to copying/cuting text, but it's not something this extension tries to address. There are different ways text selection can be prevented. For instance, CSS can be used in which case using something like [User CSS](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb?hl=en) would probably be best, in the case of filecroco.com they are using JavaScript and using something like [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en) would be best.
